-- RecommendedStats :: Talents.lua
-- Talent data logic, no UI: picks which top-player builds apply (overall / per dungeon / per
-- boss), decodes their in-game export strings, and works out per-node pick rates plus the single
-- real build that best represents what most players take. UI/TalentsWindow.lua renders it.
--
-- Data (all generated by RecommendedStatsNode, see its src/talents.js):
--   RecommendedStatsData_Talents[key]                  = { {code=, n=}, ... }   spec-wide, per content
--   RecommendedStatsData_TalentsDungeon[key][dungeon]  = { n=, builds={{code=,n=}} }
--   RecommendedStatsData_TalentsBoss[key][boss]        = { n=, difficulty=, builds={{code=,n=}} }
--   RecommendedStatsData_TalentsNames                  = { dungeons={{slug=,name=}}, bosses={...} }
-- A missing per-dungeon/per-boss entry means "too few players", so the spec-wide build is used.
-- Never falls back across content types (a raid build is not shown for M+ or the other way round).

local RS = RecommendedStats

--------------------------------------------------------------------------------
-- Export string decoding
--------------------------------------------------------------------------------
-- Format checked offline against Raider.IO's decoded loadouts for 20 specs (2026-09-21):
--   6-bit base64 chars, bits read least-significant first.
--   header: version (8) | specID (16) | tree hash (128)
--   then ONE record per node in C_Traits.GetTreeNodes(treeID) order (the same order Blizzard's own
--   import/export uses), each:
--     selected (1); if selected: purchased (1) [0 = granted for free];
--       if purchased: partial (1) [+ ranks (6) if partial], choice (1) [+ picked entry index (2)].
-- Only serialization version 2 is understood; anything else fails soft (no data) rather than
-- rendering garbage.
local SUPPORTED_VERSION = 2

local B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local B64_INDEX = {}
for i = 1, #B64 do B64_INDEX[B64:sub(i, i)] = i - 1 end

local function Take(s, width)
    local value, got = 0, 0
    while got < width do
        if s.rem == 0 then
            local idx = B64_INDEX[s.str:sub(s.pos, s.pos)]
            if not idx then s.failed = true; return 0 end -- out of data or a bad character
            s.pos = s.pos + 1
            s.cur, s.rem = idx, 6
        end
        local n = math.min(s.rem, width - got)
        local mod = 2 ^ n
        value = value + (s.cur % mod) * (2 ^ got)
        s.cur = math.floor(s.cur / mod)
        s.rem = s.rem - n
        got = got + n
    end
    return value
end

-- Returns specID, selected where selected[nodeID] = { granted=bool, ranks=n|nil, pick=n|nil }
-- (pick is a 0-based index into the node's entries), or nil if the string can't be read.
function RS:DecodeLoadout(code, nodeIDs)
    if type(code) ~= "string" or not nodeIDs then return nil end
    local s = { str = code, pos = 1, cur = 0, rem = 0, failed = false }

    local version = Take(s, 8)
    local specID = Take(s, 16)
    for _ = 1, 16 do Take(s, 8) end -- tree hash, not needed
    if s.failed or version ~= SUPPORTED_VERSION then return nil end

    local selected = {}
    for _, nodeID in ipairs(nodeIDs) do
        if Take(s, 1) == 1 then
            local rec = {}
            if Take(s, 1) == 1 then -- purchased
                if Take(s, 1) == 1 then rec.ranks = Take(s, 6) end -- partially ranked
                if Take(s, 1) == 1 then rec.pick = Take(s, 2) end  -- choice node
            else
                rec.granted = true
            end
            selected[nodeID] = rec
        end
    end
    if s.failed then return nil end
    return specID, selected
end

--------------------------------------------------------------------------------
-- The player's own talent tree (node list, in export order)
--------------------------------------------------------------------------------
function RS:GetTalentTreeInfo()
    if not (C_ClassTalents and C_Traits and GetSpecialization) then return nil end
    local specIndex = GetSpecialization()
    if not specIndex then return nil end
    local specID = GetSpecializationInfo(specIndex)
    local configID = C_ClassTalents.GetActiveConfigID and C_ClassTalents.GetActiveConfigID()
    if not (specID and configID) then return nil end

    local treeID = C_ClassTalents.GetTraitTreeForSpec and C_ClassTalents.GetTraitTreeForSpec(specID)
    if not treeID then
        local cfg = C_Traits.GetConfigInfo(configID)
        treeID = cfg and cfg.treeIDs and cfg.treeIDs[1]
    end
    if not treeID then return nil end

    local nodeIDs = C_Traits.GetTreeNodes(treeID)
    if not nodeIDs or #nodeIDs == 0 then return nil end
    return { specID = specID, configID = configID, treeID = treeID, nodeIDs = nodeIDs }
end

--------------------------------------------------------------------------------
-- Scope selection (overall / dungeon / boss) and fallback
--------------------------------------------------------------------------------
local function ScopedTable(content)
    if content == "RAID" then return RecommendedStatsData_TalentsBoss end
    return RecommendedStatsData_TalentsDungeon
end

-- Ordered list for the talents window: { {value=, name=, dedicated=bool} }. "Overall" first, then
-- every dungeon (M+) or boss (Raid) the data build knows about. dedicated=false means this spec
-- has too little data there and the row would show the spec-wide build instead.
-- The key is passed in (not RS:GetKey()) because the window has its own Raid/Mythic+ toggle,
-- independent of the stats panel's content setting.
function RS:GetTalentEntries(content)
    local L = RecommendedStats_Locale
    local entries = { { value = "OVERALL", name = L.TALENTS_SCOPE_OVERALL, dedicated = true } }
    local names = RecommendedStatsData_TalentsNames
    local list = names and (content == "RAID" and names.bosses or names.dungeons)
    if not list then return entries end

    local key = RS:GetKeyFor(content)
    local perSpec = key and ScopedTable(content) and ScopedTable(content)[key]
    for _, g in ipairs(list) do
        entries[#entries + 1] = { value = g.slug, name = g.name, dedicated = perSpec ~= nil and perSpec[g.slug] ~= nil }
    end
    return entries
end

-- Which builds apply for a content + scope: { builds=, players=, scoped=bool, difficulty=, fellBack=bool,
-- scope=, content=, key= }, or nil when this spec has no talent data at all for that content.
function RS:ResolveTalentBuilds(content, scope)
    local key = RS:GetKeyFor(content)
    if not key then return nil end
    scope = scope or "OVERALL"

    if scope ~= "OVERALL" then
        local perSpec = ScopedTable(content) and ScopedTable(content)[key]
        local entry = perSpec and perSpec[scope]
        if entry and entry.builds and #entry.builds > 0 then
            return { builds = entry.builds, players = entry.n, scoped = true, difficulty = entry.difficulty, scope = scope, content = content, key = key }
        end
    end

    local overall = RecommendedStatsData_Talents and RecommendedStatsData_Talents[key]
    if overall and #overall > 0 then
        local players = 0
        for _, b in ipairs(overall) do players = players + b.n end
        return { builds = overall, players = players, scoped = false, fellBack = scope ~= "OVERALL", scope = scope, content = content, key = key }
    end
    return nil
end

--------------------------------------------------------------------------------
-- Pick rates + best-matching real build
--------------------------------------------------------------------------------
-- Weighted by each build's player count (identical builds are shipped once with n). The displayed
-- build is a REAL player's build (always valid and importable), chosen as the one that agrees most
-- with the crowd: per node, +pick rate if the build has it, +(1 - pick rate) if it doesn't. A
-- built-from-majority-vote "consensus" build would risk breaking choice nodes and point caps.
local cache = {}

function RS:GetTalentStats(resolved, tree)
    local cacheKey = table.concat({ resolved.content, resolved.scoped and resolved.scope or "OVERALL",
        tree.specID, tree.treeID, resolved.key }, "|")
    if cache[cacheKey] then return cache[cacheKey] end

    local decoded, total = {}, 0
    local nodeCounts, pickCounts = {}, {}
    for _, b in ipairs(resolved.builds) do
        local specID, selected = RS:DecodeLoadout(b.code, tree.nodeIDs)
        if specID == tree.specID and selected then
            decoded[#decoded + 1] = { code = b.code, n = b.n, sel = selected }
            total = total + b.n
            for nodeID, rec in pairs(selected) do
                nodeCounts[nodeID] = (nodeCounts[nodeID] or 0) + b.n
                if rec.pick then
                    local pc = pickCounts[nodeID]
                    if not pc then pc = {}; pickCounts[nodeID] = pc end
                    pc[rec.pick] = (pc[rec.pick] or 0) + b.n
                end
            end
        end
    end
    if total == 0 then return nil end

    local best, bestScore
    for _, d in ipairs(decoded) do
        local score = 0
        for _, nodeID in ipairs(tree.nodeIDs) do
            local p = (nodeCounts[nodeID] or 0) / total
            score = score + (d.sel[nodeID] and p or (1 - p))
        end
        if not bestScore or score > bestScore then best, bestScore = d, score end
    end

    local stats = { total = total, distinct = #decoded, nodeCounts = nodeCounts, pickCounts = pickCounts, best = best }
    cache[cacheKey] = stats
    return stats
end
